### ISSUE TITLE
error while installing crm app

### ISSUE THREAD

**Issue by michellealva** [frappe/crm#1]
```
### App Versions
```
{
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"hrms": "15.0.0-dev",
	"print_designer": "1.0.0"
}
```
### Route
```
Workspaces/Home
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1650, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/load.py", line 68, in getdoctype
    docs = get_meta_bundle(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/load.py", line 79, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/meta.py", line 43, in get_meta
    meta = FormMeta(doctype, cached=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/meta.py", line 57, in __init__
    self.load_assets()
  File "apps/frappe/frappe/desk/form/meta.py", line 67, in load_assets
    self.add_code()
  File "apps/frappe/frappe/desk/form/meta.py", line 122, in add_code
    self.add_html_templates(path)
  File "apps/frappe/frappe/desk/form/meta.py", line 135, in add_html_templates
    for fname in os.listdir(path):
                 ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apps/crm/crm/crm/doctype/lead'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Lead",
		"with_parent": 1,
		"cached_timestamp": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoctype"
}
```
### Response Data
```
{
	"exception": "FileNotFoundError: [Errno 2] No such file or directory: 'apps/crm/crm/crm/doctype/lead'",
	"_exc_source": "crm (app)"
}
```
```

Installed and uninstalled the app, yet still getting the error. Lead is a valid doctype in erpnext, yet not able to check it.

**Comment by shariquerik** [comment]
Resolved
