### ISSUE TITLE
Bug: Error in client side when trying to create new CRM Territory via url "app/crm-territory/view/tree"

### ISSUE THREAD

**Issue by aghanem** [frappe/crm#188]
Reproduction steps:

1. Visit "CRM Territory Tree " via app/crm-territory/view/tree
2. Click New 
3. Nothing happens. 
4. Check browser console for error 

TypeError: Cannot read properties of undefined (reading 'value')
    at Object.callback (treeview.js:176:36)
    at Object.e [as success_callback] (request.js:85:16)
    at 200 (request.js:133:34)
    at Object.<anonymous> (request.js:305:6)
    at I (jquery.js:3213:31)
    at Object.fireWith [as resolveWith] (jquery.js:3343:7)
    at en (jquery.js:9617:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
    at XMLHttpRequest.r (helpers.ts:98:1)
(anonymous) @ instrument.ts:145
Show 1 more frame
Show less
3helpers.ts:100 Uncaught 

![image](https://github.com/frappe/crm/assets/2403613/cd91dcbb-1ffd-41ae-ad77-ae00dc7eaa9b)

**Comment by aghanem** [comment]
Issue is not fixed till now on the cloud version.

![image](https://github.com/frappe/crm/assets/2403613/8da9f6b9-3c5d-4313-bf4b-46628158d21c)
