### ISSUE TITLE
Error while installing crm

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/crm#2]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 296, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 305, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1108, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 935, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1288, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 932, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 520, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 605, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Twilio Agents, the DocType you're trying to open might be deleted.<br> Error: No module named 'erpnext.crm.doctype.twilio_agents'
```

Happening because erpnext and crm both are installed on the same bench (not on same site)

```
bench --site crm.local install-app crm --force

Installing crm...
> /Users/saqibansari/frappe/bench-v13/apps/frappe/frappe/modules/utils.py(244)load_doctype_module()
-> msg = f"Module import failed for {doctype}, the DocType you're trying to open might be deleted."
(Pdb) print(doctype)
Twilio Agents
(Pdb) print(module)
CRM
(Pdb) print(app)
erpnext
(Pdb)
```

**Comment by shariquerik** [comment]
Renamed the CRM module to FCRM fixed it

**Comment by teemozphoenix** [comment]
@shariquerik 
Hello , can you kindly explain the renaming of the module 

Thank you
