### ISSUE TITLE
intallation error on local

### ISSUE THREAD

**Issue by Ubaid-AI** [frappe/crm#216]
frappe version 14.67
error when installing crm 

Installing crm...
Updating DocTypes for crm           : [======================================  ] 96%An error occurred while installing crm: '/crm' is not a valid URL
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 400, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 295, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 241, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 551, in _validate
    d._validate_data_fields()
  File "apps/frappe/frappe/model/base_document.py", line 883, in _validate_data_fields
    frappe.utils.validate_url(data, throw=True)
  File "apps/frappe/frappe/utils/__init__.py", line 240, in validate_url
    frappe.throw(frappe._("'{0}' is not a valid URL").format(frappe.bold(txt)))
  File "apps/frappe/frappe/__init__.py", line 538, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 506, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 452, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: '/crm' is not a valid URL

**Comment by shariquerik** [comment]
Frappe CRM is only compatible with Frappe version 15 and above
