### ISSUE TITLE
DataError: Field not permitted in query: enabled

### ISSUE THREAD

**Issue by giulio-perosino** [frappe/crm#244]
Hello,

I'm encountering an issue with the Frappe CRM. When entering the single lead page, I get the following error:

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1808, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 66, in get_list
    validate_args(args)
  File "apps/frappe/frappe/desk/reportview.py", line 93, in validate_args
    validate_fields(data)
  File "apps/frappe/frappe/desk/reportview.py", line 121, in validate_fields
    raise_invalid_field(fieldname)
  File "apps/frappe/frappe/desk/reportview.py", line 182, in raise_invalid_field
    frappe.throw(_("Field not permitted in query") + f": {fieldname}", frappe.DataError)
  File "apps/frappe/frappe/__init__.py", line 681, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 646, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 597, in _raise_exception
    raise exc
frappe.exceptions.DataError: Field not permitted in query: enabled
```

I'm not sure why the field 'enabled' is not permitted in the query. Any help on how to resolve this would be greatly appreciated.

Thank you!

**Comment by shariquerik** [comment]
@giulio-perosino Can you share a screen recording of the issue. I am not able to reproduce the issue.

**Comment by giulio-perosino** [comment]
@shariquerik here you go. Happens also when creating a new Lead

https://github.com/frappe/crm/assets/109590131/0f954cff-9e11-42f9-a88c-d8a28f58975a

**Comment by shariquerik** [comment]
Can you check if there is CRM Fields Layout 
Check in desk

**Comment by shariquerik** [comment]
![image_2024-07-09_17-45-28 (2)](https://github.com/frappe/crm/assets/30859809/cb0053ee-8b5b-419e-9322-7f64aea0d1f2)
Run this in console it should fix your issue

**Comment by giulio-perosino** [comment]
Thanks, Shariq! This fixed the issue. I couldn’t find these steps in the docs, maybe I missed them.
