### ISSUE TITLE
get_apps returning 417

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/crm#312]
I see that this feature was just added to develop. If it's a work-in-progress, you can close this issue  I'll wait until that's done. Otherwise, when get_apps is called to generate the apps list (where 'switch to desk' used to be), http 417 is returned. Is there some specific version of frappe that's required for this to work? I'm testing on 15.38.0

```
12:58:58 web.1      | Traceback (most recent call last):
12:58:58 web.1      |   File "apps/frappe/frappe/handler.py", line 74, in execute_cmd
12:58:58 web.1      |     method = get_attr(cmd)
12:58:58 web.1      |              ^^^^^^^^^^^^^
12:58:58 web.1      |   File "apps/frappe/frappe/handler.py", line 287, in get_attr
12:58:58 web.1      |     method = frappe.get_attr(cmd)
12:58:58 web.1      |              ^^^^^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "apps/frappe/frappe/__init__.py", line 1758, in get_attr
12:58:58 web.1      |     return getattr(get_module(modulename), methodname)
12:58:58 web.1      |                    ^^^^^^^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "apps/frappe/frappe/__init__.py", line 1476, in get_module
12:58:58 web.1      |     return importlib.import_module(modulename)
12:58:58 web.1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "/home/frappe/.pyenv/versions/3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
12:58:58 web.1      |     return _bootstrap._gcd_import(name[level:], package, level)
12:58:58 web.1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
12:58:58 web.1      |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
12:58:58 web.1      |   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
12:58:58 web.1      | ModuleNotFoundError: No module named 'frappe.apps'
12:58:58 web.1      | 
12:58:58 web.1      | During handling of the above exception, another exception occurred:
12:58:58 web.1      | 
12:58:58 web.1      | Traceback (most recent call last):
12:58:58 web.1      |   File "apps/frappe/frappe/app.py", line 114, in application
12:58:58 web.1      |     response = frappe.api.handle(request)
12:58:58 web.1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "apps/frappe/frappe/api/__init__.py", line 49, in handle
12:58:58 web.1      |     data = endpoint(**arguments)
12:58:58 web.1      |            ^^^^^^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
12:58:58 web.1      |     return frappe.handler.handle()
12:58:58 web.1      |            ^^^^^^^^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "apps/frappe/frappe/handler.py", line 49, in handle
12:58:58 web.1      |     data = execute_cmd(cmd)
12:58:58 web.1      |            ^^^^^^^^^^^^^^^^
12:58:58 web.1      |   File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
12:58:58 web.1      |     frappe.throw(_("Failed to get method for command {0} with {1}").format(cmd, e))
12:58:58 web.1      |   File "apps/frappe/frappe/__init__.py", line 645, in throw
12:58:58 web.1      |     msgprint(
12:58:58 web.1      |   File "apps/frappe/frappe/__init__.py", line 610, in msgprint
12:58:58 web.1      |     _raise_exception()
12:58:58 web.1      |   File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
12:58:58 web.1      |     raise exc
12:58:58 web.1      | frappe.exceptions.ValidationError: Failed to get method for command frappe.apps.get_apps with No module named 'frappe.apps'
12:58:58 web.1      | 
12:58:58 web.1      | 172.18.0.1 - - [15/Aug/2024 12:58:58] "POST /api/method/frappe.apps.get_apps HTTP/1.1" 417 -
```

```
bench list-apps

frappe         15.38.0   version-15
erpnext        15.31.1   HEAD
helpdesk       0.10.0    develop
hrms           15.24.0   HEAD
insights       2.2.4     main
raven          1.6.4     HEAD
payments       0.0.1     version-15
network_assets 0.0.1     dev
wiki           2.0.0     master
inquire        0.0.1     main
crm            2.0.0-dev develop

**Comment by ThcDelux3** [comment]
Same issue for me

**Comment by shariquerik** [comment]
It depends on frappe make sure frappe version is latest develop

**Comment by aliarslan61** [comment]
i have same issue where i have to check to list desk so that user can return from frappe crm to the desk?
