### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by ajiragroup** [frappe/crm#37]
While trying to install beside ERPNext, I am getting this error:

```
Installing crm...
Updating DocTypes for crm           : [==================  ] 93%An error occurred while installing crm: '/crm' is not a valid URL
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 296, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 287, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 568, in _validate
    d._validate_data_fields()
  File "apps/frappe/frappe/model/base_document.py", line 898, in _validate_data_fields
    frappe.utils.validate_url(data, throw=True)
  File "apps/frappe/frappe/utils/__init__.py", line 241, in validate_url
    frappe.throw(frappe._("'{0}' is not a valid URL").format(frappe.bold(txt)))
  File "apps/frappe/frappe/__init__.py", line 571, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 543, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 497, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: '/crm' is not a valid URL
```

**Comment by parameshnalla** [comment]
Facing issue while installing the app 

`frappe@5ada679ba6f9:/workspace/development/frappe-bench/apps$ bench --site development.localhost install-app crm 

Installing crm...
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/workspace/development/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/workspace/development/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/development/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/installer.py", line 306, in install_app
    frappe.get_attr(after_install)()
  File "/workspace/development/frappe-bench/apps/crm/crm/install.py", line 11, in after_install
    add_default_lead_statuses()
  File "/workspace/development/frappe-bench/apps/crm/crm/install.py", line 44, in add_default_lead_statuses
    if frappe.db.exists("CRM Lead Status", status):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 1055, in exists
    return self.get_value(dt, dn, ignore=True, cache=cache, order_by=None)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 466, in get_value
    result = self.get_values(
  File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 563, in get_values
    out = self._get_values_from_table(
  File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 827, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 245, in sql
    traceback.print_stack()
Error in query:
('SELECT `name` FROM `tabCRM Lead Status` WHERE `name`=%(param1)s LIMIT 1', {'param1': 'Open'})
An error occurred while installing crm: Module import failed for CRM Lead Status, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.crm_lead_status'
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1409, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/.pyenv/versions/3.11.4/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frappe.core.doctype.crm_lead_status'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 306, in install_app
    frappe.get_attr(after_install)()
  File "apps/crm/crm/install.py", line 11, in after_install
    add_default_lead_statuses()
  File "apps/crm/crm/install.py", line 47, in add_default_lead_statuses
    doc = frappe.new_doc("CRM Lead Status")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1121, in new_doc
    new_doc = get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/create_new.py", line 22, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
                                              ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/create_new.py", line 35, in make_new_doc
    doc = frappe.get_doc(
          ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1266, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/base_document.py", line 69, in get_controller
    site_controllers[doctype] = import_controller(doctype)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    module = load_doctype_module(doctype, module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for CRM Lead Status, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.crm_lead_status'` Any idea on this ?

**Comment by shariquerik** [comment]
Update frappe app to latest should fix the issue

**Comment by AlaaL** [comment]
I am facing the same issue with frappe 14 latest version

Installing crm...
Updating DocTypes for crm           : [==================  ] 93%An error occurred while installing crm: '/crm' is not a valid URL
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 296, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 287, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 568, in _validate
    d._validate_data_fields()
  File "apps/frappe/frappe/model/base_document.py", line 898, in _validate_data_fields
    frappe.utils.validate_url(data, throw=True)
  File "apps/frappe/frappe/utils/__init__.py", line 241, in validate_url
    frappe.throw(frappe._("'{0}' is not a valid URL").format(frappe.bold(txt)))
  File "apps/frappe/frappe/__init__.py", line 571, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 543, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 497, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: '/crm' is not a valid URL

**Comment by shariquerik** [comment]
Frappe CRM is not compatible with Frappe version 14 it is only compatible with version 15 & above
