### ISSUE TITLE
Unable to make a call 

### ISSUE THREAD

**Issue by ajiragroup** [frappe/crm#386]
I believe I set the parameters correctly in twilio settings but I am unable to make a call.
![image](https://github.com/user-attachments/assets/10ce1553-eeeb-4e70-8db7-c48374595fd8)

This is the console.

![image](https://github.com/user-attachments/assets/15026483-620a-42a8-a323-343173eeec63)
![image](https://github.com/user-attachments/assets/54ba5a8a-5a48-4224-a164-219cc30f91b8)

```
Uncaught (in promise) Error: /api/method/frappe.client.get DoesNotExistError
    transformResponse frappeRequest.js:71
    b request.js:36
    promise callback*$b request.js:34
    LP frappeRequest.js:4
    o resources.js:99
    onSuccess Deal.vue:382
    o resources.js:109
    setup Deal.vue:423
    pr runtime-core.esm-bundler.js:2865
    Vr runtime-core.esm-bundler.js:195
    yn runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:2845
    fa runtime-core.esm-bundler.js:370
    U1 runtime-core.esm-bundler.js:408
    promise callback*V1 runtime-core.esm-bundler.js:311
    wc runtime-core.esm-bundler.js:305
    effect runtime-core.esm-bundler.js:6129
    wf reactivity.esm-bundler.js:264
    C1 reactivity.esm-bundler.js:308
    io reactivity.esm-bundler.js:1075
    set value reactivity.esm-bundler.js:1120
    A vue-router.mjs:3361
    v vue-router.mjs:3226
    promise callback*v vue-router.mjs:3193
    f vue-router.mjs:3118
    l vue-router.mjs:2204
    Vr runtime-core.esm-bundler.js:195
    yn runtime-core.esm-bundler.js:202
    n runtime-dom.esm-bundler.js:694
    lr runtime-dom.esm-bundler.js:647
    kx runtime-dom.esm-bundler.js:662
    Mx runtime-dom.esm-bundler.js:727
    m runtime-core.esm-bundler.js:5508
    y runtime-core.esm-bundler.js:5455
    b runtime-core.esm-bundler.js:5323
    W runtime-core.esm-bundler.js:6012
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6135
    T runtime-core.esm-bundler.js:6145
    j runtime-core.esm-bundler.js:5914
    R runtime-core.esm-bundler.js:5867
    b runtime-core.esm-bundler.js:5335
    W runtime-core.esm-bundler.js:6012
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6135
    T runtime-core.esm-bundler.js:6145
    j runtime-core.esm-bundler.js:5914
    R runtime-core.esm-bundler.js:5867
    b runtime-core.esm-bundler.js:5335
    x runtime-core.esm-bundler.js:5584
    A runtime-core.esm-bundler.js:5797
    b runtime-core.esm-bundler.js:5310
    x runtime-core.esm-bundler.js:5584
    A runtime-core.esm-bundler.js:5797
    b runtime-core.esm-bundler.js:5310
    x runtime-core.esm-bundler.js:5584
    m runtime-core.esm-bundler.js:5490
    y runtime-core.esm-bundler.js:5455
    b runtime-core.esm-bundler.js:5323
[frappeRequest.js:71:16](https://erp.ajiragroup.com/node_modules/frappe-ui/src/utils/frappeRequest.js)
    a resources.js:172
    o resources.js:118
    AsyncFunctionThrow self-hosted:811
    (Async: async)
    onSuccess Deal.vue:382
    o resources.js:109
    AsyncFunctionNext self-hosted:807
    (Async: async)
    setup Deal.vue:423
    pr runtime-core.esm-bundler.js:2865
    Vr runtime-core.esm-bundler.js:195
    yn runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:2845
    fa runtime-core.esm-bundler.js:370
    U1 runtime-core.esm-bundler.js:408
    (Async: promise callback)
    V1 runtime-core.esm-bundler.js:311
    wc runtime-core.esm-bundler.js:305
    effect runtime-core.esm-bundler.js:6129
    wf reactivity.esm-bundler.js:264
    C1 reactivity.esm-bundler.js:308
    io reactivity.esm-bundler.js:1075
    set value reactivity.esm-bundler.js:1120
    A vue-router.mjs:3361
    v vue-router.mjs:3226
    (Async: promise callback)
    v vue-router.mjs:3193
    f vue-router.mjs:3118
    l vue-router.mjs:2204
    Vr runtime-core.esm-bundler.js:195
    yn runtime-core.esm-bundler.js:202
    n runtime-dom.esm-bundler.js:694
    (Async: EventListener.handleEvent)
    lr runtime-dom.esm-bundler.js:647
    kx runtime-dom.esm-bundler.js:662
    Mx runtime-dom.esm-bundler.js:727
    m runtime-core.esm-bundler.js:5508
    y runtime-core.esm-bundler.js:5455
    b runtime-core.esm-bundler.js:5323
    W runtime-core.esm-bundler.js:6012
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6135
    T runtime-core.esm-bundler.js:6145
    j runtime-core.esm-bundler.js:5914
    R runtime-core.esm-bundler.js:5867
    b runtime-core.esm-bundler.js:5335
    W runtime-core.esm-bundler.js:6012
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6135
    T runtime-core.esm-bundler.js:6145
    j runtime-core.esm-bundler.js:5914
    R runtime-core.esm-bundler.js:5867
    b runtime-core.esm-bundler.js:5335
    x runtime-core.esm-bundler.js:5584
    A runtime-core.esm-bundler.js:5797
    b runtime-core.esm-bundler.js:5310
    x runtime-core.esm-bundler.js:5584
    A runtime-core.esm-bundler.js:5797
    b runtime-core.esm-bundler.js:5310
    x runtime-core.esm-bundler.js:5584
    m runtime-core.esm-bundler.js:5490
    y runtime-core.esm-bundler.js:5455
    b runtime-core.esm-bundler.js:5323

​```

**Comment by 1ubuntuuser** [comment]
The call popup works, but then says "We are sorry. Application error has occurred" 

Log found in console 

  `log.js:73 [TwilioVoice][Call] Received an error from the gateway: ConnectionError: ConnectionError (31005): Error sent from gateway in HANGUP
    at b.n [as constructor] (twilioError.js:25:28)
    at new b (generated.js:367:32)
    at s._onHangup (call.js:310:23)
    at Y.emit (events.js:153:5)
    at ne._handleTransportMessage (pstream.js:157:10)
    at Y.emit (events.js:153:5)
    at b._onSocketMessage (wstransport.js:173:19)
t.error @ log.js:73
s._onHangup @ call.js:311
Y.emit @ events.js:153
ne._handleTransportMessage @ pstream.js:157
Y.emit @ events.js:153
b._onSocketMessage @ wstransport.js:173
Show 6 more frames
Show lessUnderstand this error
CallUI.vue:505 Call ended from makeOutgoing call disconnect.`
