### ISSUE TITLE
'<strong>/crm</strong>' is not a valid URL

### ISSUE THREAD

**Issue by travnettech** [frappe/crm#40]
Installing crm...
Updating DocTypes for crm	    : [=====================================   ] 94%An error occurred while installing crm: '<strong>/crm</strong>' is not a valid URL
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 297, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 263, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 546, in _validate
    d._validate_data_fields()
  File "apps/frappe/frappe/model/base_document.py", line 879, in _validate_data_fields
    frappe.utils.validate_url(data, throw=True)
  File "apps/frappe/frappe/utils/__init__.py", line 240, in validate_url
    frappe.throw(frappe._("'{0}' is not a valid URL").format(frappe.bold(txt)))
  File "apps/frappe/frappe/__init__.py", line 540, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 508, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 454, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: '<strong>/crm</strong>' is not a valid URL

**Comment by felixlu07** [comment]
@travnettech Did you manage to find an explanation for this or how did you resolve this?
