### ISSUE TITLE
Connecting ERPNext

### ISSUE THREAD

**Issue by aliarslan61** [frappe/crm#446]
Hi im getting an error messeage when im trying to enable in ERPNext CRM Settings doctype

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 188, in set_value
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/crm/crm/fcrm/doctype/erpnext_crm_settings/erpnext_crm_settings.py", line 17, in validate
    self.create_custom_fields()
  File "apps/crm/crm/fcrm/doctype/erpnext_crm_settings/erpnext_crm_settings.py", line 39, in create_custom_fields
    from erpnext.crm.frappe_crm_api import create_custom_fields_for_frappe_crm
ModuleNotFoundError: No module named 'erpnext.crm.frappe_crm_api'

**Comment by shariquerik** [comment]
@aliarslan61 Try again

**Comment by shariquerik** [comment]
The error does not help, try again on latest version and if issue still exists reopen this issue.
