### ISSUE TITLE
CRM Develop branch Error

### ISSUE THREAD

**Issue by nilpatel42** [frappe/crm#473]
After Update to Latest Develop Branch, i Get this Error

```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 530, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 160, in update_context
    self.pymodule = frappe.get_module(self.pymodule_name)
  File "apps/frappe/frappe/__init__.py", line 1433, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/crm/crm/www/crm.py", line 8, in <module>
    from frappe.locale import (
ImportError: cannot import name 'get_date_format' from 'frappe.locale' (unknown location)
```

**Comment by jameswong3388** [comment]
I have the same issue with docker setup with 

```
frappe@09b302569303:~/frappe-bench$ bench --site all list-apps

frappe          15.50.0 UNVERSIONED
frappe_telegram 0.0.1   UNVERSIONED
```

<img width="1444" alt="Screenshot 2024-12-15 at 11 08 14 AM" src="https://github.com/user-attachments/assets/2a371fa7-1750-440b-a47f-4957f0b078d9" />

**Comment by jameswong3388** [comment]
<img width="1739" alt="Screenshot 2024-12-16 at 7 34 36 AM" src="https://github.com/user-attachments/assets/39b43de1-57a2-4744-ae02-01e97292b10e" />
this is a fresh installed Frappe CRM

**Comment by jameswong3388** [comment]
@shariquerik Can somebody look into this issue, i belive its a break on newly Frappe release [15.50.0](https://github.com/frappe/frappe/releases/tag/v15.50.0)

**Comment by shariquerik** [comment]
@jameswong3388 check this https://github.com/frappe/crm/issues/460
